import Head from "next/head";
import InnerBlog from "page-sections/inner-blogs";
import InnerBlogSection from "page-sections/inner-blogs/inner-blog-section";

const InnerBlogs = () => {
  return (
    <div>
      <Head>
        <title>InnerNews - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <InnerBlog>
        <InnerBlogSection />
      </InnerBlog>
    </div>
  );
};

export default InnerBlogs;
