import Head from "next/head";

import PrivacySection from "page-sections/privacy-section";

const PrivacyPolicy = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <PrivacySection />
    </>
  );
};

export default PrivacyPolicy;
