import Head from "next/head";
import BlogPage from "page-sections/blogs";
import JobsPage from "page-sections/blogs/jobs";

const Jobs = () => {
  return (
    <div>
      <Head>
        <title>Jobs - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <BlogPage>
        <JobsPage />
      </BlogPage>
    </div>
  );
};

export default Jobs;
