import Head from "next/head";

import OverviewSection from "page-sections/overview-section";
import AboutSection from "page-sections/overview-section/about";

const About = () => {
  return (
    <>
      <Head>
        <title>Profile - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <OverviewSection>
        <AboutSection />
      </OverviewSection>
    </>
  );
};

export default About;
