import Head from "next/head";

import ContactSection from "page-sections/contact-section";

const ContactUs = () => {
  return (
    <>
      <Head>
        <title>Contact Us - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <ContactSection />
    </>
  );
};

export default ContactUs;
