import Head from "next/head";

import FindCandidateWrapper from "page-sections/find-crew";
import AllShortlistedForm from "page-sections/find-crew/all-shortlisted";

const AllShortlisted = () => {
  return (
    <>
      <Head>
        <title>All Shortlist - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <FindCandidateWrapper>
        <AllShortlistedForm />
      </FindCandidateWrapper>
    </>
  );
};

export default AllShortlisted;
