import Head from "next/head";
import BlogPage from "page-sections/blogs";
import HandsOnPage from "page-sections/blogs/hands-on";

const HandsOn = () => {
  return (
    <div>
      <Head>
        <title>Hands On - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <BlogPage>
        <HandsOnPage />
      </BlogPage>
    </div>
  );
};

export default HandsOn;
