import React, { useState } from "react";
import Head from "next/head";
import Link from "next/link";
import * as yup from "yup";
import { useForm } from "react-hook-form";
import { yupResolver } from "@hookform/resolvers/yup";

import Input from "components/input";
import Button from "components/button";
import Container from "components/container";

import { forgetPass } from "api-services/auth";

import style from "styles/forgot.module.scss";
import HeaderComponent from "components/header-compo";
import BorderForm from "components/border-form";

const ForgotPassword = () => {
  const [success, setSuccess] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: yupResolver(schema),
  });

  const onSubmit = (data) => {
    forgetPass({ data, setSuccess });
  };

  return (
    <>
      <Head>
        <title>Forgot Password - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <HeaderComponent heading="Reset Password" />
      <Container>
        <BorderForm title="  Enter your email address below to reset your password">
          <div className={style.loginMain}>
            {success && (
              <div className={style.resetPasswordDiv}>
                <h6>
                  Your password has been reset and sent to your email address and mobile device. You
                  can now use your new password to{" "}
                  <Link href="/login">
                    <a>
                      <span>login</span>
                    </a>
                  </Link>
                </h6>
                <p>
                  If you do not receive your new password, please check your junk folder or{" "}
                  <Link href="/contact-us">
                    <a>
                      <span>contact us.</span>
                    </a>
                  </Link>
                </p>
              </div>
            )}
            <form onSubmit={handleSubmit(onSubmit)}>
              <div>
                <Input
                  star="*"
                  label="E-mail Address"
                  type="email"
                  name="email"
                  className={style.field}
                  register={register}
                  errorMessage={errors?.email?.message}
                />

                <div className={style.btnDiv}>
                  <Button title="Reset Password" />
                </div>
              </div>
            </form>
          </div>
        </BorderForm>
      </Container>
    </>
  );
};

export default ForgotPassword;

const schema = yup.object().shape({
  email: yup.string().required("Email is required").email("Please enter valid email"),
});
