/* eslint-disable @next/next/no-img-element */
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import Button from "components/button";

import talent from "public/assets/talented.svg";
import employeImg from "public/assets/employer.svg";
import tick from "public/assets/tick.webp";
import style from "./candidate-signUp.module.scss";

const CandidateCard = () => {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Sign Up - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>

      <div className={style.gridDiv}>
        {cards.map((ele, index) => (
          <div key={index} className={style.margin}>
            <div className={style.bgClass}>
              <div className={style.headingDivCard}>
                <div className={style.img}>
                  <Image src={ele.img} alt="card_img" height={60} width={60} />
                </div>
                <h1>{ele.heading}</h1>
              </div>
              <div className={style.innerDiv}>
                <p>{ele.para}</p>
                <p>{ele.para1}</p>
                <ul>
                  {ele.list.map((l, index) => (
                    <li key={index}>
                      <div className={style.img}>
                        <Image src={tick} alt="tick_icon" width={10} height={7} />
                      </div>
                      {l.li}
                    </li>
                  ))}
                </ul>
                <div className={style.btns}>
                  <Button
                    title={ele.btn1}
                    handleClick={() => router.push(ele.link)}
                    className={style.btn1}
                  />
                </div>
              </div>
            </div>
            <div className={style.divider}>
              <span>or</span>
            </div>
          </div>
        ))}
      </div>
    </>
  );
};

export default CandidateCard;

const cards = [
  {
    img: talent,
    heading: "Talented people",
    para: "Are you looking for full time job, a freelance position or an internship in the equine industry? ",
    para1: "Yehaww offers various positions through all the disciplines in:",
    list: [
      { li: "Professional barns" },
      {
        li: "Sales barns",
      },
      { li: "Breeding farms" },
      {
        li: " Transportation",
      },
      {
        li: "Administration and many more ",
      },
      {
        li: "Sign up today and find out more",
      },
    ],
    btn1: "Sign Up as Candidate",
    btn2: "Find out more",
    link: "/sign-up/candidate",
    link1: "/about-us",
  },
  {
    img: employeImg,
    heading: "Employers",
    para: "Are you looking for your next long term employee or just a freelance that can help you out for the week?",
    para1: "Yehaww can help you find:",
    list: [
      { li: "Grooms" },
      {
        li: "Riders",
      },
      { li: "Managers" },
      {
        li: "Trainers",
      },
      {
        li: "Office Personal",
      },
      {
        li: "Au pairs and many more",
      },
      {
        li: "sign up today and find out more",
      },
    ],
    btn1: "Sign Up as Employer",
    btn2: "Find out more",
    link: "/sign-up/employer",
    link1: "/about-us",
  },
];
