import Head from "next/head";

import OverviewSection from "page-sections/overview-section";
import DeleteProfile from "page-sections/overview-section/delete-account-section";

const Delete = () => {
  return (
    <>
      <Head>
        <title>Delete Profile - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <OverviewSection>
        <DeleteProfile />
      </OverviewSection>
    </>
  );
};

export default Delete;
