import Head from "next/head";

import FindCandidateWrapper from "page-sections/find-crew";
import ActivePostForm from "page-sections/find-crew/active-post-form";

const ActivePosts = () => {
  return (
    <div>
      <Head>
        <title>Active Post - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <FindCandidateWrapper>
        <ActivePostForm />
      </FindCandidateWrapper>
    </div>
  );
};

export default ActivePosts;
