import Head from "next/head";

import MyJobsSectionWrapper from "page-sections/my-jobs-section";

const JobSearch = () => {
  return (
    <div>
      <Head>
        <title>Search Jobs - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <MyJobsSectionWrapper></MyJobsSectionWrapper>
    </div>
  );
};

export default JobSearch;
