import Head from "next/head";

import MyJobsSectionWrapper from "page-sections/my-jobs-section";
import MyVideoInterview from "page-sections/my-jobs-section/my-video-interviews";

const VideoInterviews = () => {
  return (
    <div>
      <Head>
        <title>Video Interview - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <MyJobsSectionWrapper>
        <MyVideoInterview />
      </MyJobsSectionWrapper>
    </div>
  );
};

export default VideoInterviews;
