import Head from "next/head";

import FaqSection from "page-sections/faq-section";

const Faq = () => {
  return (
    <>
      <Head>
        <title>FAQ - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <FaqSection />
    </>
  );
};

export default Faq;
