import Head from "next/head";

import CookiesSection from "page-sections/cookies-section";

const CookiesPolicy = () => {
  return (
    <>
      <Head>
        <title>Cookies Policy - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <CookiesSection />
    </>
  );
};

export default CookiesPolicy;
