import Head from "next/head";

import AdvertiseForm from "page-sections/advertise-section";

const AdvertiseWithUs = () => {
  return (
    <div>
      <Head>
        <title>Advertise - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <AdvertiseForm />
    </div>
  );
};

export default AdvertiseWithUs;
