import Head from "next/head";

import FindCandidateWrapper from "page-sections/find-crew";
import CandidateSearchForm from "page-sections/find-crew/candidate-search-form";

const CandidateSearch = () => {
  return (
    <div>
      <Head>
        <title>Search Candidate - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <FindCandidateWrapper>
        <CandidateSearchForm />
      </FindCandidateWrapper>
    </div>
  );
};

export default CandidateSearch;
