import Head from "next/head";

import SingleJobPage from "page-sections/single-job";

import { GET_JOB } from "utils/endpoints";
import { getStructuredJob } from "utils/helper";

const SingleJob = ({ data }) => {
  return (
    <>
      <Head>
        <title>{data.jobTitle} - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(getStructuredJob(data)) }}
        ></script>
      </Head>
      <div style={{ minHeight: "calc(100vh - 206px)" }}>
        <SingleJobPage data={data} />
      </div>
    </>
  );
};

export const getStaticPaths = async () => {
  return {
    paths: [], //indicates that no page needs be created at build time
    fallback: "blocking", //indicates the type of fallback
  };
};

// This gets called on every request
export async function getStaticProps(context) {
  // Fetch data from external API
  const { id } = context.params;
  const res = await fetch(`${process.env.NEXT_PUBLIC_API_BASE_URL}${GET_JOB(id)}`);
  const data = await res.json();
  if (res?.status === 200) {
    // Pass data to the page via props
    return { props: { data } };
  } else if (res?.status === 409) {
    return { props: { data } };
  } else {
    return { props: {} };
  }
}

export default SingleJob;
