import Head from "next/head";

import OverviewSection from "page-sections/overview-section";
import ExperienceSection from "page-sections/overview-section/experience-section";

const Experience = () => {
  return (
    <>
      <Head>
        <title>Profile - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <OverviewSection>
        <ExperienceSection />
      </OverviewSection>
    </>
  );
};

export default Experience;
