const Joi = require("joi");

const country_list = [
  "Australia",
  "Belgium",
  "Chile",
  "Denmark",
  "Germany",
  "Ireland",
  "Mexico",
  "New Zealand",
  "Poland",
  "Saudi Arabia",
  "Switzerland",
  "United Arab Emirates",
  "Austria",
  "Canada",
  "Czech Republic",
  "France",
  "Hong Kong S.A.R.",
  "Italy",
  "Netherlands",
  "Norway",
  "Portugal",
  "Spain",
  "United Kingdom",
  "United States",
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Azerbaijan",
  "Bahamas The",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D'Ivoire (Ivory Coast)",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Democratic Republic of the Congo",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji Islands",
  "Finland",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia The",
  "Georgia",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey and Alderney",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Israel",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau S.A.R.",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Man (Isle of)",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "New Caledonia",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "Northern Mariana Islands",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory Occupied",
  "Panama",
  "Papua new Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Island",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts And Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent And The Grenadines",
  "Saint-Barthelemy",
  "Saint-Martin (French part)",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia",
  "South Korea",
  "South Sudan",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard And Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks And Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City State (Holy See)",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (US)",
  "Wallis And Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

const positionArr = [
  "Flatrider/Groom",
  "Groom/Au Pair",
  "Groom/Housekeeper",
  "Property Manager",
  "Barn Manager",
  "Polo Groom",
  "Racing Groom",
  "Jockey",
  "Stall Mucker",
  "Braider",
  "Freelance Groom",
  "Driver",
  "Freelance Driver",
  "Handyman",
  "Working Student",
  "Gardener",
  "Security",
  "Farrier",
  "Flight Groom",
  "Veterinary",
  "Dentist",
  "Chiropractor",
  "Bodyworker",
  "Nutritionist",
  "Equine Real Estate Agent",
  "Western rider",
  "Equine Therapist",
  "Equine Dental Technician",
  "Equine Nutritionist",
  "Equine Therapist",
  "Equine Veterinarian",
  "Equine Veterinarian Technician",
  "Equine Bodyworker",
  "Broodmare Manager",
  "Riding Instructor",
  "Competition Judge",
  "Show Jumping Course Designer",
  "Equine Insurance Agent",
  "Equine Product Sales Representative",
  "Event/Competition Promoter",
  "Equine Photographer/Video",
  "Ring crew/ Arena maintenance",
  "Cleaning crew",
  "Stable crew",
  "Catering",
  "Show office personnel",
  "Security",
  "Announcer",
  "Guest services",
  "VIP hostess",
  "Show manager",
  "Marketing",
  "Retail personnel",
  "Media",
  "Parking crew",
  "Property maintenance",
  "Personal Assistant",
  "Public Relations/Social Media",
  "Accountant",
  "Sales/Marketing",
  "Event Coordinator",
  "Secretary/Admin",
  "Show Rider",
  "Barn Manager",
  "Show Groom",
  "Home Groom",
  "Exercise Rider",
  "Young Horse Rider",
  "Home Groom/Flat Rider",
  "Home Groom/Manager",
  "Manager/Flat Rider",
  "Showjumping Trainer",
  "Show Rider",
  "Barn Manager",
  "Show Groom",
  "Home Groom",
  "Exercise Rider",
  "Young Horse Rider",
  "Home Groom/Flat Rider",
  "Home Groom/Manager",
  "Manager/Flat Rider",
  "Dressage Trainer",
  "Show Rider",
  "Barn Manager",
  "Show Groom",
  "Home Groom",
  "Exercise Rider",
  "Young Horse Rider",
  "Home Groom/Flat Rider",
  "Home Groom/Manager",
  "Manager/Flat Rider",
  "Eventing Trainer",
  "Barn Manager",
  "Groom",
  "Exercise Rider",
  "Hunter Trainer",
  "Hunter Rider",
  "Hunter Groom",
  "Equitation Trainer",
  "Equitation Rider",
  "Equitation Groom",
];

const stayCleanPositions = [
  "Accountant",
  "Sales/Marketing",
  "Secretary/Admin",
  "Event Coordinator",
  "Personal Assistant",
  "Accountant (Office)",
  "Sales/Marketing (Office)",
  "Secretary/Admin (Office)",
  "Event Coordinator (Office)",
  "Personal Assistant (Office)",
  "Public Relations/Social Media",
  "Public Relations/Social Media (Office)",
];

const experience = [
  "0-6 months",
  "6months-1 year",
  "1-2 years",
  "2-5 years",
  "5+ years",
  "10+ years",
];

const availability = [
  "Immediately",
  "Within 1 week",
  "1-2 weeks",
  "2-3 weeks",
  "4+ weeks",
  "Unknown",
  "Unavailable",
];

const languages = [
  { code: "ab", name: "Abkhazian" },
  { code: "aa", name: "Afar" },
  { code: "af", name: "Afrikaans" },
  { code: "ak", name: "Akan" },
  { code: "sq", name: "Albanian" },
  { code: "am", name: "Amharic" },
  { code: "ar", name: "Arabic" },
  { code: "an", name: "Aragonese" },
  { code: "hy", name: "Armenian" },
  { code: "as", name: "Assamese" },
  { code: "av", name: "Avaric" },
  { code: "ae", name: "Avestan" },
  { code: "ay", name: "Aymara" },
  { code: "az", name: "Azerbaijani" },
  { code: "bm", name: "Bambara" },
  { code: "ba", name: "Bashkir" },
  { code: "eu", name: "Basque" },
  { code: "be", name: "Belarusian" },
  { code: "bn", name: "Bengali" },
  { code: "bh", name: "Bihari languages" },
  { code: "bi", name: "Bislama" },
  { code: "bs", name: "Bosnian" },
  { code: "br", name: "Breton" },
  { code: "bg", name: "Bulgarian" },
  { code: "my", name: "Burmese" },
  { code: "ca", name: "Catalan, Valencian" },
  { code: "km", name: "Central Khmer" },
  { code: "ch", name: "Chamorro" },
  { code: "ce", name: "Chechen" },
  { code: "ny", name: "Chichewa, Chewa, Nyanja" },
  { code: "zh", name: "Chinese" },
  { code: "cu", name: "Church Slavonic, Old Bulgarian, Old Church Slavonic" },
  { code: "cv", name: "Chuvash" },
  { code: "kw", name: "Cornish" },
  { code: "co", name: "Corsican" },
  { code: "cr", name: "Cree" },
  { code: "hr", name: "Croatian" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "dv", name: "Divehi, Dhivehi, Maldivian" },
  { code: "nl", name: "Dutch, Flemish" },
  { code: "dz", name: "Dzongkha" },
  { code: "en", name: "English" },
  { code: "eo", name: "Esperanto" },
  { code: "et", name: "Estonian" },
  { code: "ee", name: "Ewe" },
  { code: "fo", name: "Faroese" },
  { code: "fj", name: "Fijian" },
  { code: "fi", name: "Finnish" },
  { code: "fr", name: "French" },
  { code: "ff", name: "Fulah" },
  { code: "gd", name: "Gaelic, Scottish Gaelic" },
  { code: "gl", name: "Galician" },
  { code: "lg", name: "Ganda" },
  { code: "ka", name: "Georgian" },
  { code: "de", name: "German" },
  { code: "ki", name: "Gikuyu, Kikuyu" },
  { code: "el", name: "Greek (Modern)" },
  { code: "kl", name: "Greenlandic, Kalaallisut" },
  { code: "gn", name: "Guarani" },
  { code: "gu", name: "Gujarati" },
  { code: "ht", name: "Haitian, Haitian Creole" },
  { code: "ha", name: "Hausa" },
  { code: "he", name: "Hebrew" },
  { code: "hz", name: "Herero" },
  { code: "hi", name: "Hindi" },
  { code: "ho", name: "Hiri Motu" },
  { code: "hu", name: "Hungarian" },
  { code: "is", name: "Icelandic" },
  { code: "io", name: "Ido" },
  { code: "ig", name: "Igbo" },
  { code: "id", name: "Indonesian" },
  { code: "ia", name: "Interlingua (International Auxiliary Language Association)" },
  { code: "ie", name: "Interlingue" },
  { code: "iu", name: "Inuktitut" },
  { code: "ik", name: "Inupiaq" },
  { code: "ga", name: "Irish" },
  { code: "it", name: "Italian" },
  { code: "ja", name: "Japanese" },
  { code: "jv", name: "Javanese" },
  { code: "kn", name: "Kannada" },
  { code: "kr", name: "Kanuri" },
  { code: "ks", name: "Kashmiri" },
  { code: "kk", name: "Kazakh" },
  { code: "rw", name: "Kinyarwanda" },
  { code: "kv", name: "Komi" },
  { code: "kg", name: "Kongo" },
  { code: "ko", name: "Korean" },
  { code: "kj", name: "Kwanyama, Kuanyama" },
  { code: "ku", name: "Kurdish" },
  { code: "ky", name: "Kyrgyz" },
  { code: "lo", name: "Lao" },
  { code: "la", name: "Latin" },
  { code: "lv", name: "Latvian" },
  { code: "lb", name: "Letzeburgesch, Luxembourgish" },
  { code: "li", name: "Limburgish, Limburgan, Limburger" },
  { code: "ln", name: "Lingala" },
  { code: "lt", name: "Lithuanian" },
  { code: "lu", name: "Luba-Katanga" },
  { code: "mk", name: "Macedonian" },
  { code: "mg", name: "Malagasy" },
  { code: "ms", name: "Malay" },
  { code: "ml", name: "Malayalam" },
  { code: "mt", name: "Maltese" },
  { code: "gv", name: "Manx" },
  { code: "mi", name: "Maori" },
  { code: "mr", name: "Marathi" },
  { code: "mh", name: "Marshallese" },
  { code: "ro", name: "Moldovan, Moldavian, Romanian" },
  { code: "mn", name: "Mongolian" },
  { code: "na", name: "Nauru" },
  { code: "nv", name: "Navajo, Navaho" },
  { code: "nd", name: "Northern Ndebele" },
  { code: "ng", name: "Ndonga" },
  { code: "ne", name: "Nepali" },
  { code: "se", name: "Northern Sami" },
  { code: "no", name: "Norwegian" },
  { code: "nb", name: "Norwegian Bokmål" },
  { code: "nn", name: "Norwegian Nynorsk" },
  { code: "ii", name: "Nuosu, Sichuan Yi" },
  { code: "oc", name: "Occitan (post 1500)" },
  { code: "oj", name: "Ojibwa" },
  { code: "or", name: "Oriya" },
  { code: "om", name: "Oromo" },
  { code: "os", name: "Ossetian, Ossetic" },
  { code: "pi", name: "Pali" },
  { code: "pa", name: "Panjabi, Punjabi" },
  { code: "ps", name: "Pashto, Pushto" },
  { code: "fa", name: "Persian" },
  { code: "pl", name: "Polish" },
  { code: "pt", name: "Portuguese" },
  { code: "qu", name: "Quechua" },
  { code: "rm", name: "Romansh" },
  { code: "rn", name: "Rundi" },
  { code: "ru", name: "Russian" },
  { code: "sm", name: "Samoan" },
  { code: "sg", name: "Sango" },
  { code: "sa", name: "Sanskrit" },
  { code: "sc", name: "Sardinian" },
  { code: "sr", name: "Serbian" },
  { code: "sn", name: "Shona" },
  { code: "sd", name: "Sindhi" },
  { code: "si", name: "Sinhala, Sinhalese" },
  { code: "sk", name: "Slovak" },
  { code: "sl", name: "Slovenian" },
  { code: "so", name: "Somali" },
  { code: "st", name: "Sotho, Southern" },
  { code: "nr", name: "South Ndebele" },
  { code: "es", name: "Spanish, Castilian" },
  { code: "su", name: "Sundanese" },
  { code: "sw", name: "Swahili" },
  { code: "ss", name: "Swati" },
  { code: "sv", name: "Swedish" },
  { code: "tl", name: "Tagalog" },
  { code: "ty", name: "Tahitian" },
  { code: "tg", name: "Tajik" },
  { code: "ta", name: "Tamil" },
  { code: "tt", name: "Tatar" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" },
  { code: "bo", name: "Tibetan" },
  { code: "ti", name: "Tigrinya" },
  { code: "to", name: "Tonga (Tonga Islands)" },
  { code: "ts", name: "Tsonga" },
  { code: "tn", name: "Tswana" },
  { code: "tr", name: "Turkish" },
  { code: "tk", name: "Turkmen" },
  { code: "tw", name: "Twi" },
  { code: "ug", name: "Uighur, Uyghur" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "uz", name: "Uzbek" },
  { code: "ve", name: "Venda" },
  { code: "vi", name: "Vietnamese" },
  { code: "vo", name: "Volap_k" },
  { code: "wa", name: "Walloon" },
  { code: "cy", name: "Welsh" },
  { code: "fy", name: "Western Frisian" },
  { code: "wo", name: "Wolof" },
  { code: "xh", name: "Xhosa" },
  { code: "yi", name: "Yiddish" },
  { code: "yo", name: "Yoruba" },
  { code: "za", name: "Zhuang, Chuang" },
  { code: "zu", name: "Zulu" },
];

const nationalities = [
  "British",
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Armenian",
  "Austrian",
  "Azerbaijani",
  "Argentinian",
  "Australian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Botswanan",
  "Bulgarian",
  "Burkinese",
  "Burundian",
  "Canadian",
  "Chinese",
  "Colombian",
  "Cuban",
  "Cambodian",
  "Cameroonian",
  "Cape Verdean",
  "Chadian",
  "Chilean",
  "Congolese",
  "Costa Rican",
  "Croat",
  "Cypriot",
  "Czech",
  "Danish",
  "Dominican",
  "Djiboutian",
  "Dominican",
  "Dutch",
  "Ecuadorean",
  "Egyptian",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Finnish",
  "French Polynesian",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Guatemalan",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Indian",
  "Ireland",
  "Israeli",
  "Italian",
  "Icelandic",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Japanese",
  "Jamaican",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "North Korean",
  "Kuwaiti",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Lithuanian",
  "LUXEMBOURG",
  "Madagascan",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Mauritanian",
  "Mauritian",
  "Monacan",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mozambican",
  "Mexican",
  "Namibian",
  "Nepalese",
  "New Zealand",
  "Nicaraguan",
  "Nigerien",
  "Nigerian",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Panamanian",
  "Guinean",
  "Paraguayan",
  "Peruvian",
  "Philippine",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Rwandan",
  "Salvadorean",
  "Samoan",
  "Saudi Arabian",
  "Senegalese",
  "Serbian",
  "Sierra Leonian",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Slomoni",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Swedish",
  "Swiss",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Swazi",
  "Taiwanese",
  "Tajik",
  "Thai",
  "Togolese",
  "Trinidadian",
  "Tunisian",
  "Turkish",
  "Turkoman",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Emirati",
  "Venezuelan",
  "Vietnamese",
  "Uruguayan",
  "Uzbek",
  "Vanuatuan",
  "Yemeni",
  "Zambian",
];

const companyTypeOptions = [
  "Barn",
  "Rider",
  "Owner",
  "Stable Manager",
  "Recruitment Agency",
  "Equestrian Business",
];

const levelOfOperationOptions = [
  "Hobby Barn",
  "Young Horse Barn",
  "Amateur Barn",
  "Professional Barn",
];

const visaOptions = [
  "Green Card / US resident",
  "B1/B2",
  "European Visa / Schengen Visa",
  "European Visa & UK residents",
  "UK work Visa",
  "American Work Visa",
  "Other Visa",
];

const jobType = ["Hands on", "Stay clean"];

const availabilityOptions = ["Immediately", "Within 2 weeks", "2-4 weeks", "4-6 weeks", "6+ weeks"];

const genderOptions = ["Male", "Female", "Rather Not Describe"];

const validInterviewQuestions = [
  "What makes you suitable for the role?",
  "What career accomplishment makes you most proud?",
  "What are your greatest strengths?",
  "What are your greatest weaknesses?",
  "Why did you leave your last position?",
  "Tell me something about yourself that isn't on your CV/resume",
  "How would you handle a personality clash in the workplace?",
];

const validateValidStringArr = (arr, required = true) =>
  Joi.string()
    .valid(...arr)
    [required ? `required` : `optional`]();

const newPositionArr = {
  "General positions": [
    "Flatrider/Groom",
    "Groom/Au Pair",
    "Groom/Housekeeper",
    "Property Manager",
    "Barn Manager",
    "Polo Groom",
    "Racing Groom",
    "Jockey",
    "Stall Mucker",
    "Braider",
    "Freelance Groom",
    "Driver",
    "Freelance Driver",
    "Handyman",
    "Working Student",
    "Gardener",
    "Security",
    "Farrier",
    "Flight Groom",
    "Veterinary",
    "Dentist",
    "Chiropractor",
    "Bodyworker",
    "Nutritionist",
    "Equine Real Estate Agent",
    "Western rider",
    "Equine Therapist",
    "Equine Dental Technician",
    "Equine Nutritionist",
    "Equine Therapist",
    "Equine Veterinarian",
    "Equine Veterinarian Technician",
    "Equine Bodyworker",
    "Broodmare Manager",
    "Riding Instructor",
    "Competition Judge",
    "Show Jumping Course Designer",
    "Equine Insurance Agent",
    "Equine Product Sales Representative",
    "Event/Competition Promoter",
    "Equine Photographer/Video",
  ],
  "Horse Show": [
    "Ring crew/ Arena maintenance",
    "Cleaning crew",
    "Stable crew",
    "Catering",
    "Show office personnel",
    "Security",
    "Announcer",
    "Guest services",
    "VIP hostess",
    "Show manager",
    "Marketing",
    "Retail personnel",
    "Media",
    "Parking crew",
    "Property maintenance",
  ],
  Office: [
    "Personal Assistant",
    "Public Relations/Social Media",
    "Accountant",
    "Sales/Marketing",
    "Event Coordinator",
    "Secretary/Admin",
  ],
  Showjumping: [
    "Show Rider",
    "Barn Manager",
    "Show Groom",
    "Home Groom",
    "Exercise Rider",
    "Young Horse Rider",
    "Home Groom/Flat Rider",
    "Home Groom/Manager",
    "Manager/Flat Rider",
    "Showjumping Trainer",
  ],
  Dressage: [
    "Show Rider",
    "Barn Manager",
    "Show Groom",
    "Home Groom",
    "Exercise Rider",
    "Young Horse Rider",
    "Home Groom/Flat Rider",
    "Home Groom/Manager",
    "Manager/Flat Rider",
    "Dressage Trainer",
  ],
  Eventing: [
    "Show Rider",
    "Barn Manager",
    "Show Groom",
    "Home Groom",
    "Exercise Rider",
    "Young Horse Rider",
    "Home Groom/Flat Rider",
    "Home Groom/Manager",
    "Manager/Flat Rider",
    "Eventing Trainer",
  ],
  Driving: ["Barn Manager", "Groom", "Exercise Rider"],
  Hunter: ["Hunter Trainer", "Hunter Rider", "Hunter Groom"],
  Equitation: ["Equitation Trainer", "Equitation Rider", "Equitation Groom"],
};

const newPositionArr1 = [
  "+General Positions",
  "Flatrider/Groom-General Positions",
  "Groom/Au Pair-General Positions",
  "Groom/Housekeeper-General Positions",
  "Property Manager-General Positions",
  "Barn Manager-General Positions",
  "Polo Groom-General Positions",
  "Racing Groom-General Positions",
  "Jockey-General Positions",
  "Stall Mucker-General Positions",
  "Braider-General Positions",
  "Freelance Groom-General Positions",
  "Driver-General Positions",
  "Freelance Driver-General Positions",
  "Handyman-General Positions",
  "Working Student-General Positions",
  "Gardener-General Positions",
  "Security-General Positions",
  "Farrier-General Positions",
  "Flight Groom-General Positions",
  "Veterinary-General Positions",
  "Dentist-General Positions",
  "Chiropractor-General Positions",
  "Bodyworker-General Positions",
  "Nutritionist-General Positions",
  "Equine Real Estate Agent-General Positions",
  "Western rider-General Positions",
  "Equine Therapist-General Positions",
  "Equine Dental Technician-General Positions",
  "Equine Nutritionist-General Positions",
  "Equine Therapist-General Positions",
  "Equine Veterinarian-General Positions",
  "Equine Veterinarian Technician-General Positions",
  "Equine Bodyworker-General Positions",
  "Broodmare Manager-General Positions",
  "Riding Instructor-General Positions",
  "Competition Judge-General Positions",
  "Show Jumping Course Designer-General Positions",
  "Equine Insurance Agent-General Positions",
  "Equine Product Sales Representative-General Positions",
  "Event/Competition Promoter-General Positions",
  "Equine Photographer/Video-General Positions",
  "+Horse Show",
  "Ring crew/ Arena maintenance-Horse Show",
  "Cleaning crew-Horse Show",
  "Stable crew-Horse Show",
  "Catering-Horse Show",
  "Show office personnel-Horse Show",
  "Security-Horse Show",
  "Announcer-Horse Show",
  "Guest services-Horse Show",
  "VIP hostess-Horse Show",
  "Show manager-Horse Show",
  "Marketing-Horse Show",
  "Retail personnel-Horse Show",
  "Media-Horse Show",
  "Parking crew-Horse Show",
  "Property maintenance-Horse Show",
  "+Office",
  "Personal Assistant-Office",
  "Public Relations/Social Media-Office",
  "Accountant-Office",
  "Sales/Marketing-Office",
  "Event Coordinator-Office",
  "Secretary/Admin-Office",
  "+Showjumping",
  "Show Rider-Showjumping",
  "Barn Manager-Showjumping",
  "Show Groom-Showjumping",
  "Home Groom-Showjumping",
  "Exercise Rider-Showjumping",
  "Young Horse Rider-Showjumping",
  "Home Groom/Flat Rider-Showjumping",
  "Home Groom/Manager-Showjumping",
  "Manager/Flat Rider-Showjumping",
  "Showjumping Trainer-Showjumping",
  "+Dressage",
  "Show Rider-Dressage",
  "Barn Manager-Dressage",
  "Show Groom-Dressage",
  "Home Groom-Dressage",
  "Exercise Rider-Dressage",
  "Young Horse Rider-Dressage",
  "Home Groom/Flat Rider-Dressage",
  "Home Groom/Manager-Dressage",
  "Manager/Flat Rider-Dressage",
  "Dressage Trainer-Dressage",
  "+Eventing",
  "Show Rider-Eventing",
  "Barn Manager-Eventing",
  "Show Groom-Eventing",
  "Home Groom-Eventing",
  "Exercise Rider-Eventing",
  "Young Horse Rider-Eventing",
  "Home Groom/Flat Rider-Eventing",
  "Home Groom/Manager-Eventing",
  "Manager/Flat Rider-Eventing",
  "Eventing Trainer-Eventing",
  "+Driving",
  "Barn Manager-Driving",
  "Groom-Driving",
  "Exercise Rider-Driving",
  "+Hunter",
  "Hunter Trainer-Hunter",
  "Hunter Rider-Hunter",
  "Hunter Groom-Hunter",
  "+Equitation",
  "Equitation Trainer-Equitation",
  "Equitation Rider-Equitation",
  "Equitation Groom-Equitation",
];

const employeesExpectation = [
  "Able to work under pressure",
  "Adaptability",
  "Attention to details",
  "Communicative",
  "Creative",
  "Diplomatic",
  "Easygoing",
  "Flexible",
  "Friendly",
  "Hardworking",
  "Honest",
  "Initiative",
  "Management skills",
  "Motivated",
  "Multi-tasking",
  "Patient",
  "Positive thinking",
  "Problem solving",
  "Punctual",
  "Reliable",
  "Responsible",
  "Sociable",
  "Stress-resistant",
  "Strong work ethic",
  "Teamworker",
  "Willing to learn",
];

module.exports = {
  country_list,
  positionArr,
  newPositionArr,
  experience,
  availability,
  stayCleanPositions,
  languages,
  companyTypeOptions,
  levelOfOperationOptions,
  visaOptions,
  availabilityOptions,
  genderOptions,
  nationalities,
  employeesExpectation,
  jobType,
  newPositionArr1,
  validateValidStringArr,
  validInterviewQuestions,
};
