export const educationOptions = [
  "Less than high school diploma",
  "High school diploma or GED",
  "Some college, but no degree",
  "Associates Degree (for example: AA, AS)",
  "Bachelor's Degree (for example: BA, BBA, and BS)",
  "Master's Degree (for example: MA, MS, and MEng)",
  "Professional Degree (for example: MD, DDS, JD)",
  "Doctorate (for example: PhD, EdD)",
];

export const genderOptions = ["Male", "Female", "Rather Not Describe"];
export const languageFluency = ["Basic", "Intermediate", "Advanced", "Fluent"];

export const visaOptions = [
  "Green Card / US resident",
  "B1/B2",
  "European Visa / Schengen Visa",
  "European Visa & UK residents",
  "UK work Visa",
  "American Work Visa",
  "Other Visa",
];

export const experience = [
  "0 - 6 months",
  "6 months - 1 year",
  "1 - 2 years",
  "2 - 5 years",
  "5+ years",
  "10+ years",
];

export const employmentTypes = [
  "Permanent Position",
  "Seasonal",
  "Temporary",
  "Freelance",
  "Volunteer",
];

export const availability = [
  "Immediately",
  "Within 2 weeks",
  "2-4 weeks",
  "4-6 weeks",
  "6 + weeks",
  "Unknown",
  "Unavailable",
];

export const currencies = [
  "EUR (€)",
  "USD ($)",
  "GBP (£)",
  "INR (₹)",
  "AUD ($)",
  "CAD ($)",
  "SGD ($)",
  "ZAR (R)",
  "NZD ($)",
  "JPY (¥)",
  "CHF (Fr)",
  "MXN ($)",
  "CNY (¥)",
  "SEK (kr)",
  "RUB (₽)",
  "HKD ($)",
  "NOK (kr)",
  "TRY (₺)",
  "KRW (₩)",
  "BRL (R$)",
];

export const skills = [
  "lipping",
  "longing",
  "longReining",
  "handlingStallion",
  "handlingYoungHorses",
  "exerciseRiding",
  "hacking",
  "breakingIn",
  "FEIExperience",
  "teaching",
  "braiding",
  "bandaging",
  "carriageDriving",
  "jumpSchool",
  "courseBuilding",
  "barnManagement",
  "eventManagement",
  "equineFirstAid",
  "travelWithHorses",
  "logisticsPlanning",
  "transportingHorses",
  "entries",
  "equinePaperwork",
  "championship",
  "sales",
  "computerSkills",
  "marketing",
  "socialMedia",
];

export const disciplines = [
  "Barrel Racing",
  "Combined Driving",
  "Dressage",
  "Endurance",
  "Eventing",
  "Jumping",
  "Para-Equestrian",
  "Reining",
  "Vaulting",
  "English Pleasure",
  "Carriage Pleasure Driving ",
  "Hunter",
  "Hunter/ Jumping Seat Equitation",
  "Parade Horse",
  "Polo",
  "Racing",
  "Roadster",
  "Saddle Seat",
  "Western",
  "Western Dressage",
  "Western / Reining Seat Equitation",
];

export const experienceLevel = [
  "Dressage",
  "Endurance",
  "Eventing",
  "Jumping",
  "Para-Equestrian",
  "Reining",
  "Vaulting",
  "English pleasure",
  "Carriage Driving",
  "Hunter",
  "Hunter/Jumping seat Equitation",
  "Parade Horse",
  "Polo",
  "Racing",
  "Western",
  "Western Dressage",
  "Western/Reining Seat Equitation",
  "Barn & facility Manager",
  "Equine Therapist",
  "Equine Dental Technician",
  "Equine Nutritionist",
  "Equine Rehabilitation Therapist",
  "Equine Veterinarian",
  "Equine Veterinarian Technician",
  "Broodmare Manager",
  "Riding Instructor",
  "Judge",
  "Show Jumping Course Designer",
  "Blacksmith/Farrier",
  "Exercise Rider",
  "Show Preparation",
  "Farm or Ranch Manager",
  "Equine Association Staff Member",
  "Equine Insurance Agent",
  "Equine Product Sales Representative",
  "Show Manager",
  "Event/Competition Promoter",
  "Clipping",
  "Children's Camp",
  "Foal Weaning",
  "Horse Transport",
  "Riding School",
  "Saddlery / Tack Store",
  "Stallion Service",
  "Trail Riding / Trekking Center",
  "Training Film / Movie",
  "Photography",
];

export const positionArr = [
  "Flatrider/Groom",
  "Groom/Au Pair",
  "Groom/Housekeeper",
  "Property Manager",
  "Barn Manager",
  "Polo Groom",
  "Racing Groom",
  "Jockey",
  "Stall Mucker",
  "Braider",
  "Freelance Groom",
  "Driver",
  "Freelance Driver",
  "Handyman",
  "Working Student",
  "Gardener",
  "Security",
  "Farrier",
  "Flight Groom",
  "Veterinary",
  "Dentist",
  "Chiropractor",
  "Bodyworker",
  "Nutritionist",
  "Equine Real Estate Agent",
  "Western rider",
  "Equine Therapist",
  "Equine Dental Technician",
  "Equine Nutritionist",
  "Equine Therapist",
  "Equine Veterinarian",
  "Equine Veterinarian Technician",
  "Equine Bodyworker",
  "Broodmare Manager",
  "Riding Instructor",
  "Competition Judge",
  "Show Jumping Course Designer",
  "Equine Insurance Agent",
  "Equine Product Sales Representative",
  "Event/Competition Promoter",
  "Equine Photographer/Video",
  "Ring crew/ Arena maintenance",
  "Cleaning crew",
  "Stable crew",
  "Catering",
  "Show office personnel",
  "Security",
  "Announcer",
  "Guest services",
  "VIP hostess",
  "Show manager",
  "Marketing",
  "Retail personnel",
  "Media",
  "Parking crew",
  "Property maintenance",
  "Personal Assistant",
  "Public Relations/Social Media",
  "Accountant",
  "Sales/Marketing",
  "Event Coordinator",
  "Secretary/Admin",
  "Show Rider",
  "Barn Manager",
  "Show Groom",
  "Home Groom",
  "Exercise Rider",
  "Young Horse Rider",
  "Home Groom/Flat Rider",
  "Home Groom/Manager",
  "Manager/Flat Rider",
  "Showjumping Trainer",
  "Show Rider",
  "Barn Manager",
  "Show Groom",
  "Home Groom",
  "Exercise Rider",
  "Young Horse Rider",
  "Home Groom/Flat Rider",
  "Home Groom/Manager",
  "Manager/Flat Rider",
  "Dressage Trainer",
  "Show Rider",
  "Barn Manager",
  "Show Groom",
  "Home Groom",
  "Exercise Rider",
  "Young Horse Rider",
  "Home Groom/Flat Rider",
  "Home Groom/Manager",
  "Manager/Flat Rider",
  "Eventing Trainer",
  "Barn Manager",
  "Groom",
  "Exercise Rider",
  "Hunter Trainer",
  "Hunter Rider",
  "Hunter Groom",
  "Equitation Trainer",
  "Equitation Rider",
  "Equitation Groom",
];

export const country_list = [
  "Australia",
  "Belgium",
  "Chile",
  "Denmark",
  "Germany",
  "Ireland",
  "Mexico",
  "New Zealand",
  "Poland",
  "Saudi Arabia",
  "Switzerland",
  "United Arab Emirates",
  "Austria",
  "Canada",
  "Czech Republic",
  "France",
  "Hong Kong S.A.R.",
  "Italy",
  "Netherlands",
  "Norway",
  "Portugal",
  "Spain",
  "United Kingdom",
  "United States",
  "Afghanistan",
  "Aland Islands",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua And Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Azerbaijan",
  "Bahamas The",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Cape Verde",
  "Cayman Islands",
  "Central African Republic",
  "Chad",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands",
  "Colombia",
  "Comoros",
  "Congo",
  "Cook Islands",
  "Costa Rica",
  "Cote D'Ivoire (Ivory Coast)",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Democratic Republic of the Congo",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "East Timor",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland Islands",
  "Faroe Islands",
  "Fiji Islands",
  "Finland",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories",
  "Gabon",
  "Gambia The",
  "Georgia",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey and Alderney",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Israel",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macau S.A.R.",
  "Macedonia",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Man (Isle of)",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "New Caledonia",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "North Korea",
  "Northern Mariana Islands",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestinian Territory Occupied",
  "Panama",
  "Papua new Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn Island",
  "Puerto Rico",
  "Qatar",
  "Reunion",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Helena",
  "Saint Kitts And Nevis",
  "Saint Lucia",
  "Saint Pierre and Miquelon",
  "Saint Vincent And The Grenadines",
  "Saint-Barthelemy",
  "Saint-Martin (French part)",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia",
  "South Korea",
  "South Sudan",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard And Jan Mayen Islands",
  "Swaziland",
  "Sweden",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad And Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks And Caicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United States Minor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City State (Holy See)",
  "Venezuela",
  "Vietnam",
  "Virgin Islands (British)",
  "Virgin Islands (US)",
  "Wallis And Futuna Islands",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const countryAndCodes = [
  { name: "Afghanistan", iso2: "AF" },
  { name: "Aland Islands", iso2: "AX" },
  { name: "Albania", iso2: "AL" },
  { name: "Algeria", iso2: "DZ" },
  { name: "American Samoa", iso2: "AS" },
  { name: "Andorra", iso2: "AD" },
  { name: "Angola", iso2: "AO" },
  { name: "Anguilla", iso2: "AI" },
  { name: "Antarctica", iso2: "AQ" },
  { name: "Antigua And Barbuda", iso2: "AG" },
  { name: "Argentina", iso2: "AR" },
  { name: "Armenia", iso2: "AM" },
  { name: "Aruba", iso2: "AW" },
  { name: "Australia", iso2: "AU" },
  { name: "Austria", iso2: "AT" },
  { name: "Azerbaijan", iso2: "AZ" },
  { name: "Bahamas The", iso2: "BS" },
  { name: "Bahrain", iso2: "BH" },
  { name: "Bangladesh", iso2: "BD" },
  { name: "Barbados", iso2: "BB" },
  { name: "Belarus", iso2: "BY" },
  { name: "Belgium", iso2: "BE" },
  { name: "Belize", iso2: "BZ" },
  { name: "Benin", iso2: "BJ" },
  { name: "Bermuda", iso2: "BM" },
  { name: "Bhutan", iso2: "BT" },
  { name: "Bolivia", iso2: "BO" },
  { name: "Bonaire, Sint Eustatius and Saba", iso2: "BQ" },
  { name: "Bosnia and Herzegovina", iso2: "BA" },
  { name: "Botswana", iso2: "BW" },
  { name: "Bouvet Island", iso2: "BV" },
  { name: "Brazil", iso2: "BR" },
  { name: "British Indian Ocean Territory", iso2: "IO" },
  { name: "Brunei", iso2: "BN" },
  { name: "Bulgaria", iso2: "BG" },
  { name: "Burkina Faso", iso2: "BF" },
  { name: "Burundi", iso2: "BI" },
  { name: "Cambodia", iso2: "KH" },
  { name: "Cameroon", iso2: "CM" },
  { name: "Canada", iso2: "CA" },
  { name: "Cape Verde", iso2: "CV" },
  { name: "Cayman Islands", iso2: "KY" },
  { name: "Central African Republic", iso2: "CF" },
  { name: "Chad", iso2: "TD" },
  { name: "Chile", iso2: "CL" },
  { name: "China", iso2: "CN" },
  { name: "Christmas Island", iso2: "CX" },
  { name: "Cocos (Keeling) Islands", iso2: "CC" },
  { name: "Colombia", iso2: "CO" },
  { name: "Comoros", iso2: "KM" },
  { name: "Congo", iso2: "CG" },
  { name: "Cook Islands", iso2: "CK" },
  { name: "Costa Rica", iso2: "CR" },
  { name: "Cote D'Ivoire (Ivory Coast)", iso2: "CI" },
  { name: "Croatia", iso2: "HR" },
  { name: "Cuba", iso2: "CU" },
  { name: "Curaçao", iso2: "CW" },
  { name: "Cyprus", iso2: "CY" },
  { name: "Czech Republic", iso2: "CZ" },
  { name: "Democratic Republic of the Congo", iso2: "CD" },
  { name: "Denmark", iso2: "DK" },
  { name: "Djibouti", iso2: "DJ" },
  { name: "Dominica", iso2: "DM" },
  { name: "Dominican Republic", iso2: "DO" },
  { name: "East Timor", iso2: "TL" },
  { name: "Ecuador", iso2: "EC" },
  { name: "Egypt", iso2: "EG" },
  { name: "El Salvador", iso2: "SV" },
  { name: "Equatorial Guinea", iso2: "GQ" },
  { name: "Eritrea", iso2: "ER" },
  { name: "Estonia", iso2: "EE" },
  { name: "Ethiopia", iso2: "ET" },
  { name: "Falkland Islands", iso2: "FK" },
  { name: "Faroe Islands", iso2: "FO" },
  { name: "Fiji Islands", iso2: "FJ" },
  { name: "Finland", iso2: "FI" },
  { name: "France", iso2: "FR" },
  { name: "French Guiana", iso2: "GF" },
  { name: "French Polynesia", iso2: "PF" },
  { name: "French Southern Territories", iso2: "TF" },
  { name: "Gabon", iso2: "GA" },
  { name: "Gambia The", iso2: "GM" },
  { name: "Georgia", iso2: "GE" },
  { name: "Germany", iso2: "DE" },
  { name: "Ghana", iso2: "GH" },
  { name: "Gibraltar", iso2: "GI" },
  { name: "Greece", iso2: "GR" },
  { name: "Greenland", iso2: "GL" },
  { name: "Grenada", iso2: "GD" },
  { name: "Guadeloupe", iso2: "GP" },
  { name: "Guam", iso2: "GU" },
  { name: "Guatemala", iso2: "GT" },
  { name: "Guernsey and Alderney", iso2: "GG" },
  { name: "Guinea", iso2: "GN" },
  { name: "Guinea-Bissau", iso2: "GW" },
  { name: "Guyana", iso2: "GY" },
  { name: "Haiti", iso2: "HT" },
  { name: "Heard Island and McDonald Islands", iso2: "HM" },
  { name: "Honduras", iso2: "HN" },
  { name: "Hong Kong S.A.R.", iso2: "HK" },
  { name: "Hong Kong S.A.R.", iso2: "HK" },
  { name: "Hungary", iso2: "HU" },
  { name: "Iceland", iso2: "IS" },
  { name: "India", iso2: "IN" },
  { name: "Indonesia", iso2: "ID" },
  { name: "Iran", iso2: "IR" },
  { name: "Iraq", iso2: "IQ" },
  { name: "Ireland", iso2: "IE" },
  { name: "Israel", iso2: "IL" },
  { name: "Italy", iso2: "IT" },
  { name: "Jamaica", iso2: "JM" },
  { name: "Japan", iso2: "JP" },
  { name: "Jersey", iso2: "JE" },
  { name: "Jordan", iso2: "JO" },
  { name: "Kazakhstan", iso2: "KZ" },
  { name: "Kenya", iso2: "KE" },
  { name: "Kiribati", iso2: "KI" },
  { name: "Kosovo", iso2: "XK" },
  { name: "Kuwait", iso2: "KW" },
  { name: "Kyrgyzstan", iso2: "KG" },
  { name: "Laos", iso2: "LA" },
  { name: "Latvia", iso2: "LV" },
  { name: "Lebanon", iso2: "LB" },
  { name: "Lesotho", iso2: "LS" },
  { name: "Liberia", iso2: "LR" },
  { name: "Libya", iso2: "LY" },
  { name: "Liechtenstein", iso2: "LI" },
  { name: "Lithuania", iso2: "LT" },
  { name: "Luxembourg", iso2: "LU" },
  { name: "Macau S.A.R.", iso2: "MO" },
  { name: "Macedonia", iso2: "MK" },
  { name: "Madagascar", iso2: "MG" },
  { name: "Malawi", iso2: "MW" },
  { name: "Malaysia", iso2: "MY" },
  { name: "Maldives", iso2: "MV" },
  { name: "Mali", iso2: "ML" },
  { name: "Malta", iso2: "MT" },
  { name: "Man (Isle of)", iso2: "IM" },
  { name: "Marshall Islands", iso2: "MH" },
  { name: "Martinique", iso2: "MQ" },
  { name: "Mauritania", iso2: "MR" },
  { name: "Mauritius", iso2: "MU" },
  { name: "Mayotte", iso2: "YT" },
  { name: "Mexico", iso2: "MX" },
  { name: "Micronesia", iso2: "FM" },
  { name: "Moldova", iso2: "MD" },
  { name: "Monaco", iso2: "MC" },
  { name: "Mongolia", iso2: "MN" },
  { name: "Montenegro", iso2: "ME" },
  { name: "Montserrat", iso2: "MS" },
  { name: "Morocco", iso2: "MA" },
  { name: "Mozambique", iso2: "MZ" },
  { name: "Myanmar", iso2: "MM" },
  { name: "Namibia", iso2: "NA" },
  { name: "Nauru", iso2: "NR" },
  { name: "Nepal", iso2: "NP" },
  { name: "Netherlands", iso2: "NL" },
  { name: "New Caledonia", iso2: "NC" },
  { name: "New Zealand", iso2: "NZ" },
  { name: "Nicaragua", iso2: "NI" },
  { name: "Niger", iso2: "NE" },
  { name: "Nigeria", iso2: "NG" },
  { name: "Niue", iso2: "NU" },
  { name: "Norfolk Island", iso2: "NF" },
  { name: "North Korea", iso2: "KP" },
  { name: "Northern Mariana Islands", iso2: "MP" },
  { name: "Norway", iso2: "NO" },
  { name: "Oman", iso2: "OM" },
  { name: "Pakistan", iso2: "PK" },
  { name: "Palau", iso2: "PW" },
  { name: "Palestinian Territory Occupied", iso2: "PS" },
  { name: "Panama", iso2: "PA" },
  { name: "Papua new Guinea", iso2: "PG" },
  { name: "Paraguay", iso2: "PY" },
  { name: "Peru", iso2: "PE" },
  { name: "Philippines", iso2: "PH" },
  { name: "Pitcairn Island", iso2: "PN" },
  { name: "Poland", iso2: "PL" },
  { name: "Portugal", iso2: "PT" },
  { name: "Puerto Rico", iso2: "PR" },
  { name: "Qatar", iso2: "QA" },
  { name: "Reunion", iso2: "RE" },
  { name: "Romania", iso2: "RO" },
  { name: "Russia", iso2: "RU" },
  { name: "Rwanda", iso2: "RW" },
  { name: "Saint Helena", iso2: "SH" },
  { name: "Saint Kitts And Nevis", iso2: "KN" },
  { name: "Saint Lucia", iso2: "LC" },
  { name: "Saint Pierre and Miquelon", iso2: "PM" },
  { name: "Saint Vincent And The Grenadines", iso2: "VC" },
  { name: "Saint-Barthelemy", iso2: "BL" },
  { name: "Saint-Martin (French part)", iso2: "MF" },
  { name: "Samoa", iso2: "WS" },
  { name: "San Marino", iso2: "SM" },
  { name: "Sao Tome and Principe", iso2: "ST" },
  { name: "Saudi Arabia", iso2: "SA" },
  { name: "Senegal", iso2: "SN" },
  { name: "Serbia", iso2: "RS" },
  { name: "Seychelles", iso2: "SC" },
  { name: "Sierra Leone", iso2: "SL" },
  { name: "Singapore", iso2: "SG" },
  { name: "Sint Maarten (Dutch part)", iso2: "SX" },
  { name: "Slovakia", iso2: "SK" },
  { name: "Slovenia", iso2: "SI" },
  { name: "Solomon Islands", iso2: "SB" },
  { name: "Somalia", iso2: "SO" },
  { name: "South Africa", iso2: "ZA" },
  { name: "South Georgia", iso2: "GS" },
  { name: "South Korea", iso2: "KR" },
  { name: "South Sudan", iso2: "SS" },
  { name: "Spain", iso2: "ES" },
  { name: "Sri Lanka", iso2: "LK" },
  { name: "Sudan", iso2: "SD" },
  { name: "Suriname", iso2: "SR" },
  { name: "Svalbard And Jan Mayen Islands", iso2: "SJ" },
  { name: "Swaziland", iso2: "SZ" },
  { name: "Sweden", iso2: "SE" },
  { name: "Switzerland", iso2: "CH" },
  { name: "Syria", iso2: "SY" },
  { name: "Taiwan", iso2: "TW" },
  { name: "Tajikistan", iso2: "TJ" },
  { name: "Tanzania", iso2: "TZ" },
  { name: "Thailand", iso2: "TH" },
  { name: "Togo", iso2: "TG" },
  { name: "Tokelau", iso2: "TK" },
  { name: "Tonga", iso2: "TO" },
  { name: "Trinidad And Tobago", iso2: "TT" },
  { name: "Tunisia", iso2: "TN" },
  { name: "Turkey", iso2: "TR" },
  { name: "Turkmenistan", iso2: "TM" },
  { name: "Turks And Caicos Islands", iso2: "TC" },
  { name: "Tuvalu", iso2: "TV" },
  { name: "Uganda", iso2: "UG" },
  { name: "Ukraine", iso2: "UA" },
  { name: "United Arab Emirates", iso2: "AE" },
  { name: "United Kingdom", iso2: "GB" },
  { name: "United States", iso2: "US" },
  { name: "United States Minor Outlying Islands", iso2: "UM" },
  { name: "Uruguay", iso2: "UY" },
  { name: "Uzbekistan", iso2: "UZ" },
  { name: "Vanuatu", iso2: "VU" },
  { name: "Vatican City State (Holy See)", iso2: "VA" },
  { name: "Venezuela", iso2: "VE" },
  { name: "Vietnam", iso2: "VN" },
  { name: "Virgin Islands (British)", iso2: "VG" },
  { name: "Virgin Islands (US)", iso2: "VI" },
  { name: "Wallis And Futuna Islands", iso2: "WF" },
  { name: "Western Sahara", iso2: "EH" },
  { name: "Yemen", iso2: "YE" },
  { name: "Zambia", iso2: "ZM" },
  { name: "Zimbabwe", iso2: "ZW" },
];

export const languages = [
  "Abkhazian",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bihari languages",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan, Valencian",
  "Central Khmer",
  "Chamorro",
  "Chechen",
  "Chichewa, Chewa, Nyanja",
  "Chinese",
  "Church Slavonic, Old Bulgarian, Old Church Slavonic",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Divehi, Dhivehi, Maldivian",
  "Dutch, Flemish",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Fulah",
  "Gaelic, Scottish Gaelic",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Gikuyu, Kikuyu",
  "Greek (Modern)",
  "Greenlandic, Kalaallisut",
  "Guarani",
  "Gujarati",
  "Haitian, Haitian Creole",
  "Hausa",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua (International Auxiliary Language Association)",
  "Interlingue",
  "Inuktitut",
  "Inupiaq",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Kinyarwanda",
  "Komi",
  "Kongo",
  "Korean",
  "Kwanyama, Kuanyama",
  "Kurdish",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Letzeburgesch, Luxembourgish",
  "Limburgish, Limburgan, Limburger",
  "Lingala",
  "Lithuanian",
  "Luba-Katanga",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Maori",
  "Marathi",
  "Marshallese",
  "Moldovan, Moldavian, Romanian",
  "Mongolian",
  "Nauru",
  "Navajo, Navaho",
  "Northern Ndebele",
  "Ndonga",
  "Nepali",
  "Northern Sami",
  "Norwegian",
  "Norwegian Bokmål",
  "Norwegian Nynorsk",
  "Nuosu, Sichuan Yi",
  "Occitan (post 1500)",
  "Ojibwa",
  "Oriya",
  "Oromo",
  "Ossetian, Ossetic",
  "Pali",
  "Panjabi, Punjabi",
  "Pashto, Pushto",
  "Persian",
  "Polish",
  "Portuguese",
  "Quechua",
  "Romansh",
  "Rundi",
  "Russian",
  "Samoan",
  "Sango",
  "Sanskrit",
  "Sardinian",
  "Serbian",
  "Shona",
  "Sindhi",
  "Sinhala, Sinhalese",
  "Slovak",
  "Slovenian",
  "Somali",
  "Sotho, Southern",
  "South Ndebele",
  "Spanish, Castilian",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tigrinya",
  "Tonga (Tonga Islands)",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Twi",
  "Uighur, Uyghur",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volap_k",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang, Chuang",
  "Zulu",
];

export const nationalities = [
  "British",
  "Afghan",
  "Albanian",
  "Algerian",
  "American",
  "Andorran",
  "Angolan",
  "Armenian",
  "Austrian",
  "Azerbaijani",
  "Argentinian",
  "Australian",
  "Bahraini",
  "Bangladeshi",
  "Barbadian",
  "Belarusian",
  "Belizean",
  "Beninese",
  "Bermudian",
  "Bhutanese",
  "Bolivian",
  "Bosnian",
  "Botswanan",
  "Bulgarian",
  "Burkinese",
  "Burundian",
  "Canadian",
  "Chinese",
  "Colombian",
  "Cuban",
  "Cambodian",
  "Cameroonian",
  "Cape Verdean",
  "Chadian",
  "Chilean",
  "Congolese",
  "Costa Rican",
  "Croat",
  "Cypriot",
  "Czech",
  "Danish",
  "Dominican",
  "Djiboutian",
  "Dominican",
  "Dutch",
  "Ecuadorean",
  "Egyptian",
  "Eritrean",
  "Estonian",
  "Ethiopian",
  "Fijian",
  "Finnish",
  "French Polynesian",
  "French",
  "Gabonese",
  "Gambian",
  "Georgian",
  "German",
  "Guatemalan",
  "Ghanaian",
  "Greek",
  "Grenadian",
  "Guinean",
  "Guyanese",
  "Haitian",
  "Honduran",
  "Hungarian",
  "Indian",
  "Ireland",
  "Israeli",
  "Italian",
  "Icelandic",
  "Indonesian",
  "Iranian",
  "Iraqi",
  "Japanese",
  "Jamaican",
  "Jordanian",
  "Kazakh",
  "Kenyan",
  "North Korean",
  "Kuwaiti",
  "Latvian",
  "Lebanese",
  "Liberian",
  "Libyan",
  "Lithuanian",
  "LUXEMBOURG",
  "Madagascan",
  "Malawian",
  "Malaysian",
  "Maldivian",
  "Malian",
  "Maltese",
  "Mauritanian",
  "Mauritian",
  "Monacan",
  "Mongolian",
  "Montenegrin",
  "Moroccan",
  "Mozambican",
  "Mexican",
  "Namibian",
  "Nepalese",
  "New Zealand",
  "Nicaraguan",
  "Nigerien",
  "Nigerian",
  "Norwegian",
  "Omani",
  "Pakistani",
  "Panamanian",
  "Guinean",
  "Paraguayan",
  "Peruvian",
  "Philippine",
  "Polish",
  "Portuguese",
  "Qatari",
  "Romanian",
  "Rwandan",
  "Salvadorean",
  "Samoan",
  "Saudi Arabian",
  "Senegalese",
  "Serbian",
  "Sierra Leonian",
  "Singaporean",
  "Slovak",
  "Slovenian",
  "Slomoni",
  "Somali",
  "South African",
  "South Korean",
  "Spanish",
  "Swedish",
  "Swiss",
  "Sri Lankan",
  "Sudanese",
  "Surinamese",
  "Swazi",
  "Taiwanese",
  "Tajik",
  "Thai",
  "Togolese",
  "Trinidadian",
  "Tunisian",
  "Turkish",
  "Turkoman",
  "Tuvaluan",
  "Ugandan",
  "Ukrainian",
  "Emirati",
  "Venezuelan",
  "Vietnamese",
  "Uruguayan",
  "Uzbek",
  "Vanuatuan",
  "Yemeni",
  "Zambian",
];

export const stayCleanPositions = [
  "Personal Assistant",
  "Public Relations/Social Media",
  "Accountant",
  "Sales/Marketing",
  "Event Coordinator",
  "Secretary/Admin",
];

export const newPositionArr = {
  "General Positions": [
    "Flatrider/Groom",
    "Groom/Au Pair",
    "Groom/Housekeeper",
    "Property Manager",
    "Barn Manager",
    "Polo Groom",
    "Racing Groom",
    "Jockey",
    "Stall Mucker",
    "Braider",
    "Freelance Groom",
    "Driver",
    "Freelance Driver",
    "Handyman",
    "Working Student",
    "Gardener",
    "Security",
    "Farrier",
    "Flight Groom",
    "Veterinary",
    "Dentist",
    "Chiropractor",
    "Bodyworker",
    "Nutritionist",
    "Equine Real Estate Agent",
    "Western rider",
    "Equine Therapist",
    "Equine Dental Technician",
    "Equine Nutritionist",
    "Equine Therapist",
    "Equine Veterinarian",
    "Equine Veterinarian Technician",
    "Equine Bodyworker",
    "Broodmare Manager",
    "Riding Instructor",
    "Competition Judge",
    "Show Jumping Course Designer",
    "Equine Insurance Agent",
    "Equine Product Sales Representative",
    "Event/Competition Promoter",
    "Equine Photographer/Video",
  ],
  "Horse Show": [
    "Ring crew/ Arena maintenance",
    "Cleaning crew",
    "Stable crew",
    "Catering",
    "Show office personnel",
    "Security",
    "Announcer",
    "Guest services",
    "VIP hostess",
    "Show manager",
    "Marketing",
    "Retail personnel",
    "Media",
    "Parking crew",
    "Property maintenance",
  ],
  Office: [
    "Personal Assistant",
    "Public Relations/Social Media",
    "Accountant",
    "Sales/Marketing",
    "Event Coordinator",
    "Secretary/Admin",
  ],
  Showjumping: [
    "Show Rider",
    "Barn Manager",
    "Show Groom",
    "Home Groom",
    "Exercise Rider",
    "Young Horse Rider",
    "Home Groom/Flat Rider",
    "Home Groom/Manager",
    "Manager/Flat Rider",
    "Showjumping Trainer",
  ],
  Dressage: [
    "Show Rider",
    "Barn Manager",
    "Show Groom",
    "Home Groom",
    "Exercise Rider",
    "Young Horse Rider",
    "Home Groom/Flat Rider",
    "Home Groom/Manager",
    "Manager/Flat Rider",
    "Dressage Trainer",
  ],
  Eventing: [
    "Show Rider",
    "Barn Manager",
    "Show Groom",
    "Home Groom",
    "Exercise Rider",
    "Young Horse Rider",
    "Home Groom/Flat Rider",
    "Home Groom/Manager",
    "Manager/Flat Rider",
    "Eventing Trainer",
  ],
  Driving: ["Barn Manager", "Groom", "Exercise Rider"],
  Hunter: ["Hunter Trainer", "Hunter Rider", "Hunter Groom"],
  Equitation: ["Equitation Trainer", "Equitation Rider", "Equitation Groom"],
};
export const newPositionArr1 = [
  "+General Positions",
  "Flatrider/Groom-General Positions",
  "Groom/Au Pair-General Positions",
  "Groom/Housekeeper-General Positions",
  "Property Manager-General Positions",
  "Barn Manager-General Positions",
  "Polo Groom-General Positions",
  "Racing Groom-General Positions",
  "Jockey-General Positions",
  "Stall Mucker-General Positions",
  "Braider-General Positions",
  "Freelance Groom-General Positions",
  "Driver-General Positions",
  "Freelance Driver-General Positions",
  "Handyman-General Positions",
  "Working Student-General Positions",
  "Gardener-General Positions",
  "Security-General Positions",
  "Farrier-General Positions",
  "Flight Groom-General Positions",
  "Veterinary-General Positions",
  "Dentist-General Positions",
  "Chiropractor-General Positions",
  "Bodyworker-General Positions",
  "Nutritionist-General Positions",
  "Equine Real Estate Agent-General Positions",
  "Western rider-General Positions",
  "Equine Therapist-General Positions",
  "Equine Dental Technician-General Positions",
  "Equine Nutritionist-General Positions",
  "Equine Therapist-General Positions",
  "Equine Veterinarian-General Positions",
  "Equine Veterinarian Technician-General Positions",
  "Equine Bodyworker-General Positions",
  "Broodmare Manager-General Positions",
  "Riding Instructor-General Positions",
  "Competition Judge-General Positions",
  "Show Jumping Course Designer-General Positions",
  "Equine Insurance Agent-General Positions",
  "Equine Product Sales Representative-General Positions",
  "Event/Competition Promoter-General Positions",
  "Equine Photographer/Video-General Positions",
  "+Horse Show",
  "Ring crew/ Arena maintenance-Horse Show",
  "Cleaning crew-Horse Show",
  "Stable crew-Horse Show",
  "Catering-Horse Show",
  "Show office personnel-Horse Show",
  "Security-Horse Show",
  "Announcer-Horse Show",
  "Guest services-Horse Show",
  "VIP hostess-Horse Show",
  "Show manager-Horse Show",
  "Marketing-Horse Show",
  "Retail personnel-Horse Show",
  "Media-Horse Show",
  "Parking crew-Horse Show",
  "Property maintenance-Horse Show",
  "+Office",
  "Personal Assistant-Office",
  "Public Relations/Social Media-Office",
  "Accountant-Office",
  "Sales/Marketing-Office",
  "Event Coordinator-Office",
  "Secretary/Admin-Office",
  "+Showjumping",
  "Show Rider-Showjumping",
  "Barn Manager-Showjumping",
  "Show Groom-Showjumping",
  "Home Groom-Showjumping",
  "Exercise Rider-Showjumping",
  "Young Horse Rider-Showjumping",
  "Home Groom/Flat Rider-Showjumping",
  "Home Groom/Manager-Showjumping",
  "Manager/Flat Rider-Showjumping",
  "Showjumping Trainer-Showjumping",
  "+Dressage",
  "Show Rider-Dressage",
  "Barn Manager-Dressage",
  "Show Groom-Dressage",
  "Home Groom-Dressage",
  "Exercise Rider-Dressage",
  "Young Horse Rider-Dressage",
  "Home Groom/Flat Rider-Dressage",
  "Home Groom/Manager-Dressage",
  "Manager/Flat Rider-Dressage",
  "Dressage Trainer-Dressage",
  "+Eventing",
  "Show Rider-Eventing",
  "Barn Manager-Eventing",
  "Show Groom-Eventing",
  "Home Groom-Eventing",
  "Exercise Rider-Eventing",
  "Young Horse Rider-Eventing",
  "Home Groom/Flat Rider-Eventing",
  "Home Groom/Manager-Eventing",
  "Manager/Flat Rider-Eventing",
  "Eventing Trainer-Eventing",
  "+Driving",
  "Barn Manager-Driving",
  "Groom-Driving",
  "Exercise Rider-Driving",
  "+Hunter",
  "Hunter Trainer-Hunter",
  "Hunter Rider-Hunter",
  "Hunter Groom-Hunter",
  "+Equitation",
  "Equitation Trainer-Equitation",
  "Equitation Rider-Equitation",
  "Equitation Groom-Equitation",
];

export const jobTypeKeys = {
  Barn: "barn",
  Rider: "rider",
  Owner: "owner",
  "Stable Manager": "stableManager",
  "Recruitment Agency": "recruitmentAgency",
  "Equestrian Business": "equestrianBusiness",
};

export const newPositionArr1Categorized = {
  "General Positions": [
    "Flatrider/Groom-General Positions",
    "Groom/Au Pair-General Positions",
    "Groom/Housekeeper-General Positions",
    "Property Manager-General Positions",
    "Barn Manager-General Positions",
    "Polo Groom-General Positions",
    "Racing Groom-General Positions",
    "Jockey-General Positions",
    "Stall Mucker-General Positions",
    "Braider-General Positions",
    "Freelance Groom-General Positions",
    "Driver-General Positions",
    "Freelance Driver-General Positions",
    "Handyman-General Positions",
    "Working Student-General Positions",
    "Gardener-General Positions",
    "Security-General Positions",
    "Farrier-General Positions",
    "Flight Groom-General Positions",
    "Veterinary-General Positions",
    "Dentist-General Positions",
    "Chiropractor-General Positions",
    "Bodyworker-General Positions",
    "Nutritionist-General Positions",
    "Equine Real Estate Agent-General Positions",
    "Western rider-General Positions",
    "Equine Therapist-General Positions",
    "Equine Dental Technician-General Positions",
    "Equine Nutritionist-General Positions",
    "Equine Therapist-General Positions",
    "Equine Veterinarian-General Positions",
    "Equine Veterinarian Technician-General Positions",
    "Equine Bodyworker-General Positions",
    "Broodmare Manager-General Positions",
    "Riding Instructor-General Positions",
    "Competition Judge-General Positions",
    "Show Jumping Course Designer-General Positions",
    "Equine Insurance Agent-General Positions",
    "Equine Product Sales Representative-General Positions",
    "Event/Competition Promoter-General Positions",
    "Equine Photographer/Video-General Positions",
  ],
  "Horse Show": [
    "Ring crew/ Arena maintenance-Horse Show",
    "Cleaning crew-Horse Show",
    "Stable crew-Horse Show",
    "Catering-Horse Show",
    "Show office personnel-Horse Show",
    "Security-Horse Show",
    "Announcer-Horse Show",
    "Guest services-Horse Show",
    "VIP hostess-Horse Show",
    "Show manager-Horse Show",
    "Marketing-Horse Show",
    "Retail personnel-Horse Show",
    "Media-Horse Show",
    "Parking crew-Horse Show",
    "Property maintenance-Horse Show",
  ],
  Office: [
    "Personal Assistant-Office",
    "Public Relations/Social Media-Office",
    "Accountant-Office",
    "Sales/Marketing-Office",
    "Event Coordinator-Office",
    "Secretary/Admin-Office",
  ],
  Showjumping: [
    "Show Rider-Showjumping",
    "Barn Manager-Showjumping",
    "Show Groom-Showjumping",
    "Home Groom-Showjumping",
    "Exercise Rider-Showjumping",
    "Young Horse Rider-Showjumping",
    "Home Groom/Flat Rider-Showjumping",
    "Home Groom/Manager-Showjumping",
    "Manager/Flat Rider-Showjumping",
    "Showjumping Trainer-Showjumping",
  ],
  Dressage: [
    "Show Rider-Dressage",
    "Barn Manager-Dressage",
    "Show Groom-Dressage",
    "Home Groom-Dressage",
    "Exercise Rider-Dressage",
    "Young Horse Rider-Dressage",
    "Home Groom/Flat Rider-Dressage",
    "Home Groom/Manager-Dressage",
    "Manager/Flat Rider-Dressage",
    "Dressage Trainer-Dressage",
  ],
  Eventing: [
    "Show Rider-Eventing",
    "Barn Manager-Eventing",
    "Show Groom-Eventing",
    "Home Groom-Eventing",
    "Exercise Rider-Eventing",
    "Young Horse Rider-Eventing",
    "Home Groom/Flat Rider-Eventing",
    "Home Groom/Manager-Eventing",
    "Manager/Flat Rider-Eventing",
    "Eventing Trainer-Eventing",
  ],
  Driving: ["Barn Manager-Driving", "Groom-Driving", "Exercise Rider-Driving"],
  Hunter: ["Hunter Trainer-Hunter", "Hunter Rider-Hunter", "Hunter Groom-Hunter"],
  Equitation: [
    "Equitation Trainer-Equitation",
    "Equitation Rider-Equitation",
    "Equitation Groom-Equitation",
  ],
};

export const employeesExpectation = [
  "Able to work under pressure",
  "Adaptability",
  "Attention to details",
  "Communicative",
  "Creative",
  "Diplomatic",
  "Easygoing",
  "Flexible",
  "Friendly",
  "Hardworking",
  "Honest",
  "Initiative",
  "Management skills",
  "Motivated",
  "Multi-tasking",
  "Patient",
  "Positive thinking",
  "Problem solving",
  "Punctual",
  "Reliable",
  "Responsible",
  "Sociable",
  "Stress-resistant",
  "Strong work ethic",
  "Teamworker",
  "Willing to learn",
];
