import Head from "next/head";

import MyJobsSectionWrapper from "page-sections/my-jobs-section";
import MyJobsTab from "page-sections/my-jobs-section/my-jobs-tab";

const MyJobs = () => {
  return (
    <div>
      <Head>
        <title>My Jobs - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <MyJobsSectionWrapper>
        <MyJobsTab />
      </MyJobsSectionWrapper>
    </div>
  );
};

export default MyJobs;
