import Head from "next/head";
import BlogPage from "page-sections/blogs";
import AllArticlesPage from "page-sections/blogs/all-articles";

const News = () => {
  return (
    <div>
      <Head>
        <title>All Articles - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <BlogPage>
        <AllArticlesPage />
      </BlogPage>
    </div>
  );
};
export default News;
