import Head from "next/head";

import OverviewSection from "page-sections/overview-section";
import ChangePassword from "page-sections/overview-section/change-password-section";

const ChangePasswordPage = () => {
  return (
    <>
      <Head>
        <title>Change Password - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <OverviewSection>
        <ChangePassword />
      </OverviewSection>
    </>
  );
};

export default ChangePasswordPage;
