import Head from "next/head";

import MyJobsSection from "page-sections/my-jobs-section";

const MyJob = () => {
  return (
    <>
      <Head>
        <title>My Jobs - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <MyJobsSection />
    </>
  );
};

export default MyJob;
