import Head from "next/head";
import BlogPage from "page-sections/blogs";
import CompanyPage from "page-sections/blogs/company";

const Company = () => {
  return (
    <div>
      <Head>
        <title>Company - Yehaww</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="\assets\imgs\logo.webp" />
      </Head>
      <BlogPage>
        <CompanyPage />
      </BlogPage>
    </div>
  );
};

export default Company;
